# Generated by Django 3.1.3 on 2020-11-22 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('Nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('Apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.CharField(blank=True, max_length=200, null=True)),
                ('Grado', models.CharField(blank=True, max_length=200, null=True)),
                ('Seccion', models.CharField(blank=True, max_length=200, null=True)),
                ('Genero', models.CharField(blank=True, max_length=200, null=True)),
                ('nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('fechaingreso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('Apellido',),
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Materia', models.CharField(max_length=130)),
                ('Nota_Final', models.CharField(max_length=130)),
                ('Fecha_Ingreso', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.alumno')),
            ],
            options={
                'ordering': ('Nombre_Materia',),
            },
        ),
        migrations.CreateModel(
            name='Asignacion_Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.alumno')),
                ('Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.materia')),
            ],
        ),
    ]
