# Generated by Django 3.1.3 on 2020-11-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='Alumno',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nacimiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
