# Generated by Django 3.1.3 on 2020-11-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201122_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='Nota_Final',
        ),
        migrations.AddField(
            model_name='asignacion_materia',
            name='Nota_Final',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
